<?php
session_start();
require_once 'config.php';

// Cek apakah user sudah login dan rolenya adalah User
if (!isset($_SESSION['username']) || !isset($_SESSION['role']) || $_SESSION['role'] !== 'User') {
    header('Location: index.php');
    exit();
}

// Ambil data transaksi penerimaan dari database
// Tabel `penerimaan` saat ini hanya punya id, deskripsi, jumlah.
// Kolom lain seperti No Terima, Nama Barang, Jenis Barang, Nama Petugas, Nama Supplier, Tanggal Terima, Jam Terima perlu disesuaikan dengan struktur database riil.
$sql = "SELECT * FROM penerimaan";
$result = mysqli_query($conn, $sql);
$penerimaan_data = [];
if (mysqli_num_rows($result) > 0) {
    while($row = mysqli_fetch_assoc($result)) {
        $penerimaan_data[] = $row;
    }
}
?>

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transaksi Penerimaan (User)</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.bootstrap5.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <style>
        body { background: #f8f9fa; }
        .card { border: none; border-radius: 12px; box-shadow: 0 2px 16px rgba(44,62,80,0.06); }
        #penerimaanTable_wrapper .btn { margin-right: 5px; }
        #penerimaanTable_wrapper .dataTables_filter { margin-bottom: 10px; }
        #penerimaanTable_wrapper .dataTables_length { margin-bottom: 10px; }
        .dataTables_wrapper .dataTables_filter { margin-left: auto; }
    </style>
</head>
<body>
    <div class="container py-4">
        <h4 class="mb-3" style="font-weight:500; color:#3a3a3a;">Transaksi Penerimaan</h4>
        <div class="card p-4">
            <div class="mb-3">
                <h6 class="mb-2">Daftar Penerimaan</h6>
                <div class="row g-3 mb-3">
                    <div class="col-md-auto">
                        <label for="filterJenis" class="form-label">Filter Jenis Barang</label>
                        <select id="filterJenis" class="form-select form-select-sm">
                            <option value="">-- Silahkan Pilih --</option>
                            <!-- Options akan ditambahkan via JavaScript/PHP -->
                        </select>
                    </div>
                     <div class="col-md-auto">
                        <label for="filterTanggal" class="form-label">Filter Tanggal</label>
                        <input type="text" id="filterTanggal" class="form-control form-control-sm" placeholder="Pilih Tanggal">
                    </div>
                    <!-- Search box akan dibuat otomatis oleh DataTables -->
                    <div class="col-md-auto ms-auto">
                         <!-- Search input will be generated by DataTables -->
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table id="penerimaanTable" class="table table-striped table-hover" style="width:100%">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>No Terima</th>
                            <th>Nama Barang</th>
                            <th>Jenis Barang</th>
                            <th>Jumlah</th>
                            <th>Nama Petugas</th>
                            <th>Nama Supplier</th>
                            <th>Tanggal Terima</th>
                            <th>Jam Terima</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $no = 1; foreach ($penerimaan_data as $terima): ?>
                        <tr>
                            <td><?php echo $no++; ?></td>
                            <td><?php echo "TR" . sprintf('%010d', $terima['id']); // Dummy No Terima ?></td>
                            <td><?php echo htmlspecialchars($terima['deskripsi']); // Menggunakan deskripsi sebagai Nama Barang ?></td>
                            <td><?php echo ""; // Placeholder Jenis Barang ?></td>
                            <td><?php echo htmlspecialchars($terima['jumlah']); ?></td>
                            <td><?php echo ""; // Placeholder Nama Petugas ?></td>
                            <td><?php echo ""; // Placeholder Nama Supplier ?></td>
                            <td><?php echo ""; // Placeholder Tanggal Terima ?></td>
                            <td><?php echo ""; // Placeholder Jam Terima ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.bootstrap5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <script>
        $(document).ready(function() {
            var table = $('#penerimaanTable').DataTable({
                 layout: {
                    topStart: {
                        buttons: ['copyHtml5', 'excelHtml5', 'csvHtml5', 'pdfHtml5']
                    }
                },
                // DataTables will automatically create the search input and pagination
            });

            // Initialize Flatpickr for date filtering (requires data in the corresponding column)
            flatpickr("#filterTanggal", {
                 dateFormat: "Y-m-d", // Adjust based on your date format
                 // More Flatpickr options if needed
            });

             // Example of custom filter for Jenis Barang (requires data in table column 3 - Jenis Barang)
            $('#filterJenis').on('change', function() {
                table.column(3) // 3 is the index for 'Jenis Barang' column (0-indexed)
                      .search(this.value)
                      .draw();
            });

            // Example of custom filter for Tanggal (requires data in table column 7 - Tanggal Terima)
            $('#filterTanggal').on('change', function() {
                 table.column(7) // 7 is the index for 'Tanggal Terima' column (0-indexed)
                       .search(this.value)
                       .draw();
            });

        });
    </script>
</body>
</html> 