<?php
session_start();
require_once 'config.php';

// Cek apakah user sudah login dan rolenya adalah User
if (!isset($_SESSION['username']) || !isset($_SESSION['role']) || $_SESSION['role'] !== 'User') {
    header('Location: index.php');
    exit();
}

// Ambil data transaksi pengeluaran dari database
// Tabel `pengeluaran` saat ini hanya punya id, deskripsi, jumlah.
// Kolom lain seperti No Keluar, Nama Barang, Jenis Barang, Jumlah, Nama Petugas, Nama Pengambil, Tanggal Keluar, Jam Keluar perlu disesuaikan dengan struktur database riil.
$sql = "SELECT * FROM pengeluaran";
$result = mysqli_query($conn, $sql);
$pengeluaran_data = [];
if (mysqli_num_rows($result) > 0) {
    while($row = mysqli_fetch_assoc($result)) {
        $pengeluaran_data[] = $row;
    }
}
?>

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transaksi Pengeluaran (User)</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css" rel="stylesheet">
     <link href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.bootstrap5.min.css" rel="stylesheet">
    <style>
        body { background: #f8f9fa; }
        .card { border: none; border-radius: 12px; box-shadow: 0 2px 16px rgba(44,62,80,0.06); }
        #pengeluaranTable_wrapper .btn { margin-right: 5px; }
        #pengeluaranTable_wrapper .dataTables_filter { margin-bottom: 10px; }
        #pengeluaranTable_wrapper .dataTables_length { margin-bottom: 10px; }
        .dataTables_wrapper .dataTables_filter { margin-left: auto; }
    </style>
</head>
<body>
    <div class="container py-4">
        <h4 class="mb-3" style="font-weight:500; color:#3a3a3a;">Transaksi Pengeluaran</h4>
        <div class="card p-4">
            <div class="mb-3">
                <h6 class="mb-2">Daftar Pengeluaran</h6>
                 <div class="row g-3 mb-3">
                    <!-- Filters like Jenis Barang and Tanggal can be added here if needed, similar to Transaksi Penerimaan -->
                     <div class="col-md-auto ms-auto">
                         <!-- Search input and export buttons will be generated by DataTables -->
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table id="pengeluaranTable" class="table table-striped table-hover" style="width:100%">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>No Keluar</th>
                            <th>Nama Barang</th>
                            <th>Jenis Barang</th>
                            <th>Jumlah</th>
                            <th>Nama Petugas</th>
                            <th>Nama Pengambil</th>
                            <th>Tanggal Keluar</th>
                            <th>Jam Keluar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $no = 1; foreach ($pengeluaran_data as $keluar): ?>
                        <tr>
                            <td><?php echo $no++; ?></td>
                             <td><?php echo "TK" . sprintf('%010d', $keluar['id']); // Dummy No Keluar ?></td>
                            <td><?php echo htmlspecialchars($keluar['deskripsi']); // Menggunakan deskripsi sebagai Nama Barang ?></td>
                            <td><?php echo ""; // Placeholder Jenis Barang ?></td>
                            <td><?php echo htmlspecialchars($keluar['jumlah']); ?></td>
                            <td><?php echo ""; // Placeholder Nama Petugas ?></td>
                            <td><?php echo ""; // Placeholder Nama Pengambil ?></td>
                            <td><?php echo ""; // Placeholder Tanggal Keluar ?></td>
                            <td><?php echo ""; // Placeholder Jam Keluar ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
     <script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.bootstrap5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.colVis.min.js"></script>
    
    <script>
        $(document).ready(function() {
            $('#pengeluaranTable').DataTable({
                 layout: {
                    topStart: {
                        buttons: ['copyHtml5', 'excelHtml5', 'csvHtml5', 'pdfHtml5']
                    }
                },
                // DataTables will automatically create the search input and pagination
            });

            // You can add custom filters here if needed, similar to Transaksi Penerimaan

        });
    </script>
</body>
</html> 